"""empty message

Revision ID: 37a82bf141ff
Revises: 7c260e555d63
Create Date: 2024-09-10 13:35:46.019946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37a82bf141ff'
down_revision: Union[str, None] = '7c260e555d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'tempo_producao')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('tempo_producao', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
