"""atualiza parametros da coluna atualizado_em da tabela de clientes

Revision ID: e4cd53545244
Revises: 41b4d709e5ef
Create Date: 2024-09-03 17:56:40.184591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4cd53545244'
down_revision: Union[str, None] = '41b4d709e5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
